### ISSUE TITLE
Potential issue with downloading Tweets on Quote Retweets

### ISSUE THREAD

**Issue by GD-NTB** [newtykins/twitdown#2]
unable to download twitter video on a quote retweet
https://twitter.com/arekushi14/status/1493279138399932422
![image](https://user-images.githubusercontent.com/30124989/153919195-ea312e02-150b-49ce-a969-7440094d7d57.png)

**Comment by isitreallyalive** [comment]
This thread had been deleted, might have been an issue there. Either way, I have rewritten the way that the videos are extracted in the next update, so install that when it comes out (:
